### PR TITLE
Remove generated pdf files according to the core update

### PR DESCRIPTION
**Pull request by me2r036**
Remove generated pdf files according to the core update

### CODE REVIEW

**Comment by fooman** [comment]
@me2r036 Thank you for this pull request. I think it's a good change and I would like to include it. Unfortunately reading the corresponding change in core [here](https://github.com/magento/magento2/commit/b358932812325776ca46824aaf15f8795d990984#diff-e2da9ec41b6d0b3e9b658997403168e2R81) I believe that merging your changes mean that the only supported Magento version is 2.3.1 (as opposed to 2.1/2.2/2.3) as we would be calling `strlen` on an array. Please correct me if that is not the case.

**Comment by me2r036** [comment]
@fooman From what I can see the code should work with ^2.2.6. You can see the updated commit [here](https://github.com/magento/magento2/commit/d3a7b9729405842e680fd5fafb09285de09ce30b#diff-e2da9ec41b6d0b3e9b658997403168e2), so the strlen function works on the actual file content rather than an array.

**Comment by fooman** [comment]
Thanks for looking into this. Would you mind also updating this [line](https://github.com/fooman/printorderpdf-implementation-m2/blob/develop/composer.json#L17)
to reflect the updated dependencies, ie
`"magento/framework": "^101.0.6 | ^102.0.0",`

Please note I will not yet merge this even with the changes just yet as I still want to maintain 2.1 compatibility. However once I am ready to drop this I can merge this in.

**Comment by fooman** [comment]
@me2r036 let's merge your PR into this repo with the above changes onto a new branch. That way it should get picked up by packagist and people could already use with 
`composer require fooman/printorderpdf-implementation-m2:dev-feature/remove-generated-pdf-file`

**Comment by fooman** [comment]
Good stuff - thank you!

**Comment by me2r036** [comment]
@fooman That's great, thanks :)

**Pull request merged**
